#!/bin/sh

NB=10
INTERVALLE=60
REP_S=sondes
REP_M=mesures


while getopts "n:i:s:m:" option
do
	case $option in
		n)
			NB=$OPTARG
			shift;shift;;
		i)
			INTERVALLE=$OPTARG 
			shift;shift;;
		s)
			REP_S=$OPTARG 
			shift;shift;;
		m)
			REP_M=$OPTARG 
			shift;shift;;
	esac
done


if [ $# -eq 0 ]
then
	echo "usage : $0 [-n nb] [-i duree] [-s rep_sondes] [-m rep_mesures] sonde1 sonde2 ..." >&2
	exit 1
fi


TEST=$( echo $INTERVALLE | grep -o "[hms]" | cat )
if [ "$TEST" != "" ]
then
	HEURES=$( echo "$INTERVALLE" | grep -oE '[0-9]+h' | sed 's/h//' | cat )
	if [ "$HEURES" = "" ]
	then HEURES=0
	fi
	MINUTES=$( echo "$INTERVALLE" | grep -oE '[0-9]+m' | sed 's/m//' | cat )
	if [ "$MINUTES" = "" ]
	then MINUTES=0
	fi
	SECONDES=$( echo "$INTERVALLE" | grep -oE '[0-9]+s' | sed 's/s//' | cat )
	if [ "$SECONDES" = "" ]
	then SECONDES=0
	fi
	INTERVALLE=$(( \( $HEURES \* 3600 \) + \( $MINUTES \* 60 \) + $SECONDES ))
fi

if [ ! -d $REP_M ]
then 
	mkdir $REP_M
fi

for SONDE in $*
do
	touch $REP_M/$SONDE
	echo "# $( $REP_S/$SONDE -t ) / $( hostname )" > $REP_M/$SONDE
done

COMPTEUR=0

while [ $COMPTEUR -lt $NB ]
do
	for SONDE in $*
	do
		echo "$( date +%Y-%m-%d\ %H:%M:%S )	$( $REP_S/$SONDE )" >> $REP_M/$SONDE
	done
	sleep $INTERVALLE
	COMPTEUR=$(( $COMPTEUR + 1 ))
done


exit 0
